### PR TITLE
Style the blog page for individual articles

### PR DESCRIPTION
**Pull request by jysandy**
Closes [SC-3363](https://app.shortcut.com/nilenso/story/3363/blog-style-the-display-page-for-individual-articles)

### CODE REVIEW

**Comment by tfidfwastaken** [comment]
When there's no description on the author, there's no space between the bottom ruler and the author's name. We should add some.
image

Also, the author's name should be of weight 500 according to the design.

The body text also feels too uncomfortably offset to the right. `md:w-8/12` on the blog content div looks a lot better than the current `md:w-9/12`.

The author bio is a bit too wide on larger screens, with a small gap to its right. This can be rectified by setting the padding to `md:pr-20`, which looks much better after I tried it.

The heading is also not aligned with the author box (it's a bit lower). Let's change `my-3` to `mb-3 -mt-3.5`. The negative top margin makes the heading slightly above the top of the author box, but visually looks more aligned.

Image is squished on portrait tablets:
image

Let's make the phone font size a tad bit smaller.

**Comment by shhivam** [comment]
Screenshot 2023-01-27 at 2 55 44 PM
Should this still show up on the blog post page?

**Comment by jysandy** [comment]
@shhivam that shouldn't be there. Which blog post were you looking at?

**Comment by jysandy** [comment]
@shhivam there appears to be a discrepancy between the deploy preview and the code. This doesn't appear on localhost.

**Comment by shhivam** [comment]
@jysandy cool cool, we will do a sanity check after we deploy

**Comment by jysandy** [comment]
All of these comments should be addressed. I didn't add the negative margin to the article title, because the current margin matches the design.

**Comment by jysandy** [comment]
Missed reducing the font size on phones. We can perhaps pick that up later.

**Pull request merged**
